version: "3"

services:
  producer:
    container_name: twitter_kafka_streaming_producer
    build: "./tweets-producer"
    depends_on:
      - kafka
    restart: on-failure
    volumes:
      - ./tweets-producer:/tweets-producer
      - ./config.ini:/tweets-producer/config.ini
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  zookeeper:
    container_name: twitter_kafka_streaming_zookeeper
    image: wurstmeister/zookeeper:3.4.6
    restart: on-failure
    expose:
      - "2181"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  kafka:
    container_name: twitter_kafka_streaming_kafka
    image: wurstmeister/kafka:2.12-2.4.0
    depends_on:
      - zookeeper
    restart: on-failure
    ports:
      - "9092:9092"
    expose:
      - "9093"
    volumes:
      - ./persistence/kafka:/tmp/kafka-logs
    environment:
      - "KAFKA_BROKER_ID=1"
      - "KAFKA_LISTENERS=INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092"
      - "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
      - "KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9093,OUTSIDE://localhost:9092"
      - "KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE"
      - "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181"
      - "KAFKA_CREATE_TOPICS=tweets:1:1"
      - "KAFKA_LOG_DIRS=/tmp/kafka-logs"
      - "KAFKA_LOG_RETENTION_HOURS=24"
      - "KAFKA_LOG_CLEANUP_POLICY=delete"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  default:
    external:
      name: twitter_kafka_streaming_network